//! Data models for event clustering

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Configuration for the clustering engine
#[derive(Debug, Clone)]
pub struct ClusterConfig {
    /// Cosine similarity threshold for merging articles into the same cluster (0.0-1.0)
    /// Higher values produce more, smaller clusters
    pub similarity_threshold: f64,

    /// Minimum number of articles to form a valid cluster
    pub min_cluster_size: usize,

    /// Maximum number of articles to load from OpenSearch per batch
    pub batch_size: usize,

    /// Whether to generate vLLM summaries for clusters
    pub generate_summaries: bool,

    /// Filter by category (optional)
    pub category: Option<String>,

    /// Filter articles published after this date (optional)
    pub since: Option<String>,

    /// Maximum number of articles to process (0 = unlimited)
    pub max_articles: usize,

    /// Output directory for cluster JSON files
    pub output_dir: String,
}

impl Default for ClusterConfig {
    fn default() -> Self {
        Self {
            similarity_threshold: 0.75,
            min_cluster_size: 2,
            batch_size: 500,
            generate_summaries: false,
            category: None,
            since: None,
            max_articles: 0,
            output_dir: "./output/clusters".to_string(),
        }
    }
}

/// A single article within a cluster
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClusterArticle {
    /// Article document ID (oid_aid)
    pub id: String,

    /// Article title
    pub title: String,

    /// Article category
    pub category: String,

    /// Publisher name
    #[serde(skip_serializing_if = "Option::is_none")]
    pub publisher: Option<String>,

    /// Publication date (ISO 8601)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub published_at: Option<String>,

    /// Article URL
    pub url: String,

    /// Cosine similarity to the cluster centroid
    pub similarity_to_centroid: f64,
}

/// An event cluster — a group of articles covering the same event
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EventCluster {
    /// Unique event ID (e.g., "evt_20260215_001")
    pub event_id: String,

    /// Event title (generated by LLM or from highest-scoring article)
    pub title: String,

    /// Event summary (generated by LLM, empty if not generated)
    #[serde(default)]
    pub summary: String,

    /// Articles in this cluster
    pub articles: Vec<ClusterArticle>,

    /// Number of articles
    pub article_count: usize,

    /// Primary category (most frequent among articles)
    pub category: String,

    /// Earliest publication date among articles
    #[serde(skip_serializing_if = "Option::is_none")]
    pub first_seen: Option<String>,

    /// Latest publication date among articles
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<String>,

    /// Average internal cosine similarity
    pub avg_similarity: f64,

    /// Cluster creation timestamp
    pub created_at: DateTime<Utc>,
}

/// Full output of a clustering run
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClusterOutput {
    /// Clustering run metadata
    pub metadata: ClusterMetadata,

    /// Event clusters
    pub events: Vec<EventCluster>,
}

/// Metadata about a clustering run
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClusterMetadata {
    /// Total articles processed
    pub total_articles: usize,

    /// Total clusters formed
    pub total_clusters: usize,

    /// Articles assigned to clusters
    pub clustered_articles: usize,

    /// Articles not assigned (noise/singletons)
    pub unclustered_articles: usize,

    /// Similarity threshold used
    pub similarity_threshold: f64,

    /// Minimum cluster size used
    pub min_cluster_size: usize,

    /// Category filter applied
    #[serde(skip_serializing_if = "Option::is_none")]
    pub category_filter: Option<String>,

    /// Date filter applied
    #[serde(skip_serializing_if = "Option::is_none")]
    pub since_filter: Option<String>,

    /// When clustering was run
    pub created_at: DateTime<Utc>,

    /// Processing duration in seconds
    pub duration_secs: f64,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_cluster_config_defaults() {
        let config = ClusterConfig::default();
        assert!((config.similarity_threshold - 0.75).abs() < f64::EPSILON);
        assert_eq!(config.min_cluster_size, 2);
        assert_eq!(config.batch_size, 500);
        assert!(!config.generate_summaries);
        assert!(config.category.is_none());
        assert!(config.since.is_none());
        assert_eq!(config.max_articles, 0);
        assert_eq!(config.output_dir, "./output/clusters");
    }

    #[test]
    fn test_cluster_article_serialization() {
        let article = ClusterArticle {
            id: "001_0015812889".to_string(),
            title: "Test Article".to_string(),
            category: "politics".to_string(),
            publisher: Some("TestPub".to_string()),
            published_at: Some("2026-02-15T10:00:00Z".to_string()),
            url: "https://example.com/article".to_string(),
            similarity_to_centroid: 0.89,
        };

        let json = serde_json::to_string(&article).expect("should serialize");
        assert!(json.contains("001_0015812889"));
        assert!(json.contains("0.89"));

        let deserialized: ClusterArticle =
            serde_json::from_str(&json).expect("should deserialize");
        assert_eq!(deserialized.id, "001_0015812889");
    }

    #[test]
    fn test_event_cluster_serialization() {
        let cluster = EventCluster {
            event_id: "evt_20260215_001".to_string(),
            title: "Test Event".to_string(),
            summary: String::new(),
            articles: vec![],
            article_count: 0,
            category: "politics".to_string(),
            first_seen: Some("2026-02-15".to_string()),
            last_updated: Some("2026-02-16".to_string()),
            avg_similarity: 0.85,
            created_at: Utc::now(),
        };

        let json = serde_json::to_string_pretty(&cluster).expect("should serialize");
        assert!(json.contains("evt_20260215_001"));
        assert!(json.contains("0.85"));
    }

    #[test]
    fn test_cluster_output_serialization() {
        let output = ClusterOutput {
            metadata: ClusterMetadata {
                total_articles: 100,
                total_clusters: 5,
                clustered_articles: 80,
                unclustered_articles: 20,
                similarity_threshold: 0.75,
                min_cluster_size: 2,
                category_filter: Some("politics".to_string()),
                since_filter: None,
                created_at: Utc::now(),
                duration_secs: 12.5,
            },
            events: vec![],
        };

        let json = serde_json::to_string(&output).expect("should serialize");
        let deserialized: ClusterOutput =
            serde_json::from_str(&json).expect("should deserialize");
        assert_eq!(deserialized.metadata.total_articles, 100);
        assert_eq!(deserialized.metadata.total_clusters, 5);
    }

    #[test]
    fn test_optional_fields_skipped_in_serialization() {
        let article = ClusterArticle {
            id: "001_002".to_string(),
            title: "Test".to_string(),
            category: "society".to_string(),
            publisher: None,
            published_at: None,
            url: "https://example.com".to_string(),
            similarity_to_centroid: 0.9,
        };

        let json = serde_json::to_string(&article).expect("should serialize");
        assert!(!json.contains("publisher"));
        assert!(!json.contains("published_at"));
    }
}
